In [15]:
import pandas as pd

# Limpieza y Procesamiento de Datos

## 1.

In [16]:
df_jugadores = pd.read_csv("jugadores.csv") # Cargar jugadores.csv en un DataFrame
df_jugadores.head() # Mostrar las primeras filas del DataFrame para verificar su contenido

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,keeper_performance_cspct,keeper_penalty_kicks_pkatt,keeper_penalty_kicks_pka,keeper_penalty_kicks_pksv,keeper_penalty_kicks_pkm,keeper_penalty_kicks_savepct,keeper_playing_time_90s,nat3,valor_mercado_eur,posicion_tm
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,22.6,4.0,3.0,0.0,1.0,0.0,31.0,CZE,7000000.0,Goalkeeper
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,4500000.0,Centre-Back
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,2200000.0,Centre-Back
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,5500000.0,Centre-Back
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,7000000.0,Right-Back

## 2.

### a)
Todas las selecciones tienen 26 jugadores, solo canada tiene 25

In [17]:
df_jugadores["seleccion"].nunique() # Cuántas selecciones distintas hay

48

In [18]:
df_jugadores.groupby("seleccion").size() # Cuántos jugadores hay por selección

seleccion
Algeria                   26
Argentina                 26
Australia                 26
Austria                   25
Belgium                   26
Bosnia and Herzegovina    26
Brazil                    26
Canada                    25
Cape Verde                26
Colombia                  26
Croatia                   26
Curacao                   26
Czech Republic            26
DR Congo                  26
Ecuador                   26
Egypt                     26
England                   26
France                    26
Germany                   26
Ghana                     26
Haiti                     26
Iran                      26
Iraq                      26
Ivory Coast               26
Japan                     26
Jordan                    25
Mexico                    26
Morocco                   26
Netherlands               26
New Zealand               26
Norway                    26
Panama                    26
Paraguay                  26
Portugal                  26
Qatar                     26
Saudi Arabia              26
Scotland                  26
Senegal                   26
South Africa              26
South Korea               26
Spain                     26
Sweden                    26
Switzerland               26
Tunisia                   26
Turkey                    26
United States             26
Uruguay                   26
Uzbekistan                26
dtype: int64

### b)

In [19]:
df_jugadores["club"].nunique()

449

In [20]:
cantidad_clubes = df_jugadores.groupby("club").size()
cantidad_clubes[cantidad_clubes>=10]

club
Al-Hilal               12
Arsenal                16
Atlético Madrid        12
Barcelona              15
Bayern Munich          18
Borussia Dortmund      11
Crystal Palace         12
Fenerbahçe             10
Galatasaray            11
Liverpool              11
Manchester City        19
Manchester United      12
Milan                  10
PSV Eindhoven          10
Paris Saint-Germain    16
Real Madrid            10
Slavia Prague          10
dtype: int64

### c)
El rango etario dominante es entre 24 y 30 años

In [21]:
df_rango_etario = df_jugadores.copy() # Crear una copia del DataFrame para trabajar con el rango etario

rango_etario = lambda edad: "A" if edad < 24 else ("B" if edad <= 30 else "C")
df_rango_etario["rango_etario"] = [rango_etario(edad) for edad in df_rango_etario["edad"]]
df_rango_etario.rango_etario.head()

0    B
1    B
2    C
3    B
4    C
Name: rango_etario, dtype: str

In [22]:
top_cinco_ranking_fifa = ["Argentina", "Francia", "España", "Inglaterra", "Brasil"]
df_top_cinco = df_rango_etario[df_rango_etario["seleccion"].isin(top_cinco_ranking_fifa)]
cantidad_por_rango_etario = df_top_cinco.groupby("rango_etario").size()
cantidad_por_rango_etario

rango_etario
A     3
B    15
C     8
dtype: int64

## 3.

In [23]:
variables = ["standard_playing_time_mp", "shooting_90s", "misc_performance_fls", "playing_time_starts_starts"]
for variable in variables:
		cantidad_con_variable = df_jugadores[variable].notna().sum()
		porcentaje_con_variable = (cantidad_con_variable / len(df_jugadores)) * 100
		print(f"{variable}: {cantidad_con_variable} jugadores, {porcentaje_con_variable:.2f}% de cobertura")

standard_playing_time_mp: 921 jugadores, 73.98% de cobertura
shooting_90s: 922 jugadores, 74.06% de cobertura
misc_performance_fls: 889 jugadores, 71.41% de cobertura
playing_time_starts_starts: 476 jugadores, 38.23% de cobertura

In [24]:
variables_playing_time = [col for col in df_jugadores.columns if col.startswith("playing_time_")]
df_jugadores.drop(columns=variables_playing_time, inplace=True)
df_jugadores.head()

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,keeper_performance_cspct,keeper_penalty_kicks_pkatt,keeper_penalty_kicks_pka,keeper_penalty_kicks_pksv,keeper_penalty_kicks_pkm,keeper_penalty_kicks_savepct,keeper_playing_time_90s,nat3,valor_mercado_eur,posicion_tm
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,22.6,4.0,3.0,0.0,1.0,0.0,31.0,CZE,7000000.0,Goalkeeper
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,4500000.0,Centre-Back
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,2200000.0,Centre-Back
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,5500000.0,Centre-Back
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,7000000.0,Right-Back

## 4.

In [28]:
col_ratios = ["shooting_standard_sh", "shooting_standard_sot","shooting_standard_sotpct","shooting_standard_sh_per_90","shooting_standard_sot_per_90"]
df_jugadores[col_ratios].isna().sum()

shooting_standard_sh            356
shooting_standard_sot           356
shooting_standard_sotpct        451
shooting_standard_sh_per_90     356
shooting_standard_sot_per_90    356
dtype: int64

In [32]:
df_jugadores[col_ratios] = df_jugadores[col_ratios].fillna(0)
df_jugadores

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,keeper_performance_cspct,keeper_penalty_kicks_pkatt,keeper_penalty_kicks_pka,keeper_penalty_kicks_pksv,keeper_penalty_kicks_pkm,keeper_penalty_kicks_savepct,keeper_playing_time_90s,nat3,valor_mercado_eur,posicion_tm
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,22.6,4.0,3.0,0.0,1.0,0.0,31.0,CZE,7000000.0,Goalkeeper
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,4500000.0,Centre-Back
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,2200000.0,Centre-Back
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,5500000.0,Centre-Back
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,7000000.0,Right-Back
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,1241,Panama,22,GK,Orlando Mosquera,1994-12-25,31,47,0,Al-Fayha,...,21.9,6.0,2.0,2.0,2.0,50.0,32.0,PAN,350000.0,Goalkeeper
1241,1242,Panama,23,DF,Michael Amir Murillo,1996-02-11,30,93,9,Beşiktaş,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN,7000000.0,Right-Back
1242,1243,Panama,24,FW,Azarias Londoño,2001-06-21,24,10,0,Universidad Católica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN,175000.0,Centre-Forward
1243,1244,Panama,25,DF,Roderick Miller,1992-04-03,34,50,2,Turan Tovuz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175000.0,Centre-Back
1244,1245,Panama,26,DF,Jorge Gutiérrez,1998-09-01,27,18,0,Deportivo La Guaira,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325000.0,Left-Back

## 5.

## 6.

## 7.